export const dummyData = {
  classes: [
    {
      id: 1,
      title: "Advanced React Development",
      instructor: "Dr. Sarah Johnson",
      date: "Today, December 20",
      time: "2:00 PM - 4:00 PM",
      duration: "2 hours",
      status: "live",
    },
    {
      id: 2,
      title: "Database Design Fundamentals",
      instructor: "Prof. Michael Rodriguez",
      date: "Tomorrow, December 21",
      time: "10:00 AM - 11:30 AM",
      duration: "1.5 hours",
      status: "upcoming",
    },
    {
      id: 3,
      title: "Machine Learning Basics",
      instructor: "Dr. Emily Chen",
      date: "December 23, 2024",
      time: "1:00 PM - 3:00 PM",
      duration: "2 hours",
      status: "upcoming",
    },
  ],
  pastSessions: [
    {
      id: 1,
      title: "Introduction to React Hooks",
      date: "December 18, 2024",
      duration: "1h 45m",
      views: 127,
      recordingUrl: "/recordings/react-hooks",
    },
    {
      id: 2,
      title: "State Management with Redux",
      date: "December 16, 2024",
      duration: "2h 15m",
      views: 89,
      recordingUrl: "/recordings/redux",
    },
    {
      id: 3,
      title: "Database Normalization",
      date: "December 14, 2024",
      duration: "1h 30m",
      views: 156,
      recordingUrl: "/recordings/db-normalization",
    },
  ],
  notes: [
    {
      id: 1,
      title: "React Hooks Comprehensive Guide",
      content: "Detailed explanation of useState, useEffect, useContext...",
      subject: "React",
      preview:
        "Detailed explanation of useState, useEffect, useContext, and custom hooks. Includes practical examples and best practices for modern React development.",
      lastModified: "2 days ago",
    },
    {
      id: 2,
      title: "Database Normalization Notes",
      content: "Step-by-step process of database normalization...",
      subject: "Database",
      preview:
        "Step-by-step process of database normalization from 1NF to 3NF. Includes examples of denormalization and when to apply each normal form.",
      lastModified: "1 week ago",
    },
    {
      id: 3,
      title: "Design Patterns Cheat Sheet",
      content: "Common design patterns including Singleton, Observer...",
      subject: "Design",
      preview:
        "Quick reference for common design patterns including Singleton, Observer, Factory, and Strategy patterns with implementation examples.",
      lastModified: "3 days ago",
    },
  ],
  quizzes: [
    {
      id: 1,
      title: "React Fundamentals Quiz",
      description: "Test your knowledge of React components, state, and props",
      questions: 15,
      duration: "30 minutes",
      points: 50,
      status: "in_progress",
      progress: 8,
      score: 0,
      dueDate: "December 25, 2024",
      completedDate: null,
    },
    {
      id: 2,
      title: "Database Design Assessment",
      description:
        "Comprehensive test on ER diagrams, normalization, and SQL queries",
      questions: 20,
      duration: "45 minutes",
      points: 75,
      status: "completed",
      progress: 20,
      score: 68,
      dueDate: "December 15, 2024",
      completedDate: "December 14, 2024",
    },
    {
      id: 3,
      title: "UI/UX Design Principles",
      description:
        "Test your understanding of design fundamentals and user experience",
      questions: 12,
      duration: "25 minutes",
      points: 40,
      status: "available",
      progress: 0,
      score: 0,
      dueDate: "December 30, 2024",
      completedDate: null,
    },
  ],
};
